development:
 adapter: postgresql
 encoding: unicode
 database: pickle_dev
 host: localhost
 pool: 5
 username: onyx
 password: password

staging:
 adapter: postgresql
 encoding: unicode
 database: pickle_staging

production:
 adapter: postgresql
 encoding: unicode
 database: pickle_production